// Code generated by "stringer -type=SExprType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Atom-0]
	_ = x[List-1]
	_ = x[Nil-2]
}

const _SExprType_name = "AtomListNil"

var _SExprType_index = [...]uint8{0, 4, 8, 11}

func (i SExprType) String() string {
	if i < 0 || i >= SExprType(len(_SExprType_index)-1) {
		return "SExprType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SExprType_name[_SExprType_index[i]:_SExprType_index[i+1]]
}
