// Code generated by "stringer -type=TokType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Const-0]
	_ = x[OpenPar-1]
	_ = x[ClosePar-2]
	_ = x[Space-3]
	_ = x[Dunno-4]
	_ = x[Eof-5]
}

const _TokType_name = "ConstOpenParCloseParSpaceDunnoEof"

var _TokType_index = [...]uint8{0, 5, 12, 20, 25, 30, 33}

func (i TokType) String() string {
	if i < 0 || i >= TokType(len(_TokType_index)-1) {
		return "TokType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokType_name[_TokType_index[i]:_TokType_index[i+1]]
}
