// Code generated by "stringer -type=TokType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Const-0]
	_ = x[Op-1]
	_ = x[OpenPar-2]
	_ = x[ClosePar-3]
	_ = x[Space-4]
	_ = x[Dunno-5]
	_ = x[Eof-6]
}

const _TokType_name = "ConstOpOpenParCloseParSpaceDunnoEof"

var _TokType_index = [...]uint8{0, 5, 7, 14, 22, 27, 32, 35}

func (i TokType) String() string {
	if i < 0 || i >= TokType(len(_TokType_index)-1) {
		return "TokType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokType_name[_TokType_index[i]:_TokType_index[i+1]]
}
