// Code generated by "stringer -type=sexprType"; DO NOT EDIT.

package expr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[sexprTypeAtom-0]
	_ = x[sexprTypeList-1]
	_ = x[sexprTypeNil-2]
}

const _sexprType_name = "sexprTypeAtomsexprTypeListsexprTypeNil"

var _sexprType_index = [...]uint8{0, 13, 26, 38}

func (i sexprType) String() string {
	if i >= sexprType(len(_sexprType_index)-1) {
		return "sexprType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sexprType_name[_sexprType_index[i]:_sexprType_index[i+1]]
}
