// Code generated by "stringer -type=tokenType"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokenTypeConst-0]
	_ = x[tokenTypeOp-1]
	_ = x[tokenTypeIdent-2]
	_ = x[tokenTypeOpenPar-3]
	_ = x[tokenTypeClosePar-4]
	_ = x[tokenTypeSpace-5]
	_ = x[tokenTypeInvalid-6]
	_ = x[tokenTypeEof-7]
}

const _tokenType_name = "tokenTypeConsttokenTypeOptokenTypeIdenttokenTypeOpenPartokenTypeClosePartokenTypeSpacetokenTypeInvalidtokenTypeEof"

var _tokenType_index = [...]uint8{0, 14, 25, 39, 55, 72, 86, 102, 114}

func (i tokenType) String() string {
	if i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
